name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44

    - name: Set up matrix
      id: set-up-matrix
      run: |
        changed_microservices=$(echo '${{ steps.changed-files.outputs.all_modified_files }}' | tr ' ' '\n' | cut -d/ -f2 | uniq)
        echo '${{ steps.changed-files.outputs.all_modified_files }}' | tr ' ' '\n' | cut -d/ -f2 | uniq
        echo "$changed_microservices"
        echo "matrix=${changed_microservices}" >> $GITHUB_ENV

    - name: CI/CD
      run: |
        pwd
        if [[ -n "${{ env.matrix }}" ]]; then
          echo 'cd Micros/${{ env.matrix }}'
          cd Micros/${{ env.matrix }}
          sh ./test.sh
        else
          echo "No folder changed"
        fi
        
        
