name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v1

    - name: Set up matrix
      id: set-up-matrix
      run: |
        changed_microservices=$(echo '${{ steps.changed-files.outputs.all_modified_files }}' | tr ' ' '\n' | cut -d/ -f2 | uniq)
        echo "::set-output name=matrix::$(echo "$changed_microservices" | jq -R -s -c 'split("\n")')"

    - name: CI/CD
      run: |
        cd Micros/${{ matrix.microservice }}
        bash ci-cd.sh
