name: Monorepo

on: 
  workflow_dispatch:
  push:
    branches: main

jobs:
  listfiles:
    runs-on: ubuntu-latest
    outputs:
      changedfiles: ${{ steps.listchangedfiles.outputs.changedfiles }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'Micros/'

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          ARRAY=()
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            ARRAY+=($file)
          done
          echo "DEBUG: All changed files: $ARRAY"
          matrix=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${ARRAY[@]}")
          echo $matrix
          echo "changedfiles=${matrix}" >> GITHUB_OUTPUT


        
  changedfiles:
    needs: listfiles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        changedfiles: ${{ fromJson(needs.listfiles.outputs.changedfiles) }}
      max-parallel: 3
    steps:
      - name: Download files from repo
        uses: actions/checkout@v4

      - name: Print matrix var
        run: |
          echo "DEBUG: Matrix component"

